/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TransactionType } from "./TransactionType";
import { TransactionTypeCountArgs } from "./TransactionTypeCountArgs";
import { TransactionTypeFindManyArgs } from "./TransactionTypeFindManyArgs";
import { TransactionTypeFindUniqueArgs } from "./TransactionTypeFindUniqueArgs";
import { DeleteTransactionTypeArgs } from "./DeleteTransactionTypeArgs";
import { TransactionTypeService } from "../transactionType.service";
@graphql.Resolver(() => TransactionType)
export class TransactionTypeResolverBase {
  constructor(protected readonly service: TransactionTypeService) {}

  async _transactionTypesMeta(
    @graphql.Args() args: TransactionTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TransactionType])
  async transactionTypes(
    @graphql.Args() args: TransactionTypeFindManyArgs
  ): Promise<TransactionType[]> {
    return this.service.transactionTypes(args);
  }

  @graphql.Query(() => TransactionType, { nullable: true })
  async transactionType(
    @graphql.Args() args: TransactionTypeFindUniqueArgs
  ): Promise<TransactionType | null> {
    const result = await this.service.transactionType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TransactionType)
  async deleteTransactionType(
    @graphql.Args() args: DeleteTransactionTypeArgs
  ): Promise<TransactionType | null> {
    try {
      return await this.service.deleteTransactionType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
